# Generated by Django 6.1.2 on 2026-10-09 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('motto', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=100)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_positions', models.BooleanField(default=True, help_text='Compute and display student ranking/positions on results')),
                ('grading_system', models.CharField(default='STANDARD', max_length=50)),
                ('academic_calendar_type', models.CharField(default='THREE_TERM', max_length=50)),
                ('receipt_prefix', models.CharField(default='REC', max_length=20)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('admission_number_prefix', models.CharField(default='SMS', max_length=20)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'School Administrator'), ('PRINCIPAL', 'Principal / Head of School'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar / Accountant')], default='TEACHER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'user')},
            },
        ),
    ]
