# Generated by Django 6.1.2 on 2026-10-09 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. 2024/2025', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_type', models.CharField(choices=[('FIRST_TERM', 'First Term'), ('SECOND_TERM', 'Second Term'), ('THIRD_TERM', 'Third Term')], max_length=30)),
                ('name', models.CharField(help_text='e.g. First Term', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassArm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', help_text='e.g. Gold, Blue, A, or empty', max_length=50)),
            ],
            options={
                'ordering': ['class_level__order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Primary 1, JSS 1, SS 2', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(choices=[('NURSERY', 'Nursery / Pre-School'), ('PRIMARY', 'Primary School'), ('JUNIOR_SECONDARY', 'Junior Secondary School'), ('SENIOR_SECONDARY', 'Senior Secondary School')], default='PRIMARY', max_length=30)),
                ('order_index', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Mathematics, English Language', max_length=150)),
                ('code', models.CharField(blank=True, default='', help_text='e.g. MTH, ENG', max_length=30)),
                ('category', models.CharField(choices=[('GENERAL', 'General / Core'), ('SCIENCES', 'Sciences'), ('ARTS_HUMANITIES', 'Arts & Humanities'), ('COMMERCIAL', 'Commercial / Business'), ('VOCATIONAL', 'Vocational / Technical'), ('LANGUAGES', 'Languages')], default='GENERAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(help_text='Unique staff ID within school', max_length=50)),
                ('qualification', models.CharField(blank=True, default='', max_length=150)),
                ('specialization', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_arm__class_level__order_index', 'subject__name'],
            },
        ),
    ]
